# Generated by Django 4.2 on 2023-05-30 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_oders_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='oders_name',
            new_name='order_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='oders_address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='oders_discount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='oders_place_at',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='oders_quantity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='oders_time',
        ),
        migrations.AddField(
            model_name='orders',
            name='discount',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_address',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_at',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_price',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='quanity_of_order',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='StudentsAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(blank=True, max_length=19, null=True)),
                ('house_number', models.IntegerField(blank=True, max_length=5, null=True)),
                ('city', models.CharField(blank=True, max_length=18, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('pincode', models.IntegerField(blank=True, max_length=6, null=True)),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.students')),
            ],
        ),
    ]
