# Generated by Django 4.2 on 2023-06-02 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_oders_name_orders_order_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='mobile_number',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='students',
            name='date_or_birth',
        ),
        migrations.AddField(
            model_name='students',
            name='birth',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')]),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='studentsaddress',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_addresses', to='users.students'),
        ),
    ]
